from PyQt5 import QtCore, QtGui, QtWidgets
import image
import sys
import option
import insert
from PyQt5.QtWidgets import QMessageBox
class F:

    def exam(self, MainWindow,password):

        def sumbit(self) :
            try :
            	stuname= self.lineEdit.text();
            	stuname1=self.lineEdit_2.text();
            	comment=self.lineEdit_5.text();
            	course=self.lineEdit_4.text();
            	sid=self.lineEdit_3.text();
            	examstart1=self.comboBox.currentText();
            	examend3=self.comboBox_4.currentText();
            	examstart2=self.comboBox_2.currentText();
            	examstart3=self.comboBox_3.currentText();
            	examend1=self.comboBox_5.currentText();
            	examend2=self.comboBox_6.currentText();
            	examst=examstart1+"-"+examstart2+"-"+examstart3;
            	exame=examend1+"-"+examend2+"-"+examend3;
            	student_name= stuname+" "+stuname1;
            	insert.examform(student_name,sid,course,examst,exame,comment);
            	print("stdname ", stuname);
            	print("stuname1 ", stuname1);
            	print("sid ",sid);
            	print("course ",course);
            	print("comment ",comment);
            	print("examstart1 ",examstart1);
            	print("examstart2 ",examstart2);
            	print("examstart3 ",examstart3);
            	print("examend1 ",examend1);
            	print("examend2 ",examend2);
            	print("examend3 ",examend3);
            	print("name : ",student_name);
            	print("examstart : ",examst);
            	print("examend : ",exame);
            	msg=QMessageBox()
            	msg.setText("Sucessfully Sumbited");
            	msg.setWindowTitle(" ");
            	msg.setIcon(QMessageBox.Information)
            	x=msg.exec_()
            	MainWindow.close();            
            except :
            	msg=QMessageBox()
            	msg.setText("You've Already Applied");
            	msg.setWindowTitle(" ");
            	msg.setIcon(QMessageBox.Critical)
            	x=msg.exec_()
            	MainWindow.close();

        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/newPrefix/watermark.PNG"))
        self.label_9.setScaledContents(True)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(210, 310, 73, 31))
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setEditable(False)
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setItemText(32, "")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(180, 410, 91, 21))
        self.label_15.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 151, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(440, 410, 91, 21))
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 390, 131, 21))
        self.label_12.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(400, 140, 91, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(440, 340, 91, 21))
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(470, 380, 101, 31))
        self.comboBox_4.setAutoFillBackground(False)
        self.comboBox_4.setEditable(False)
        self.comboBox_4.setDuplicatesEnabled(False)
        self.comboBox_4.setFrame(True)
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 221, 41))
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(320, 310, 121, 31))
        self.comboBox_2.setAutoFillBackground(False)
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setDuplicatesEnabled(False)
        self.comboBox_2.setFrame(True)
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 511, 31))
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(470, 310, 101, 31))
        self.comboBox_3.setAutoFillBackground(False)
        self.comboBox_3.setEditable(False)
        self.comboBox_3.setDuplicatesEnabled(False)
        self.comboBox_3.setFrame(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 530, 93, 28))
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(300, 340, 91, 21))
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(-10, 460, 131, 21))
        self.label_16.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_16.setObjectName("label_16")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(300, 410, 91, 21))
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 70, 779, 7))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(210, 380, 73, 31))
        self.comboBox_5.setAutoFillBackground(False)
        self.comboBox_5.setEditable(False)
        self.comboBox_5.setDuplicatesEnabled(False)
        self.comboBox_5.setFrame(True)
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.setItemText(32, "")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 170, 201, 61))
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(210, 140, 91, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 320, 131, 21))
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(210, 110, 171, 31))
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(400, 110, 171, 31))
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(210, 450, 461, 71))
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(210, 250, 331, 31))
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(320, 380, 121, 31))
        self.comboBox_6.setAutoFillBackground(False)
        self.comboBox_6.setEditable(False)
        self.comboBox_6.setDuplicatesEnabled(False)
        self.comboBox_6.setFrame(True)
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(210, 180, 111, 31))
        self.lineEdit_3.setText(password);
        self.lineEdit_3.setReadOnly(True);
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(0, 250, 201, 31))
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_7.setObjectName("label_7")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(180, 340, 91, 21))
        self.label_17.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_17.setObjectName("label_17")
        MainWindow.setCentralWidget(self.centralwidget)
        """self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)"""
        self.label_6.setText("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600;\">Student Registration </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600;\">Number </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600; color:#ff0000;\">  *</span></p></body></html>")
        MainWindow.setWindowTitle("Exam Registration Form")
        self.comboBox.setItemText(1,"1")
        self.comboBox.setItemText(2,"2")
        self.comboBox.setItemText(3,"3")
        self.comboBox.setItemText(4,"4")
        self.comboBox.setItemText(5,"5")
        self.comboBox.setItemText(6,"6")
        self.comboBox.setItemText(7,"7")
        self.comboBox.setItemText(8, "8")
        self.comboBox.setItemText(9,"9")
        self.comboBox.setItemText(10,"10")
        self.comboBox.setItemText(11,"11")
        self.comboBox.setItemText(12,"12")
        self.comboBox.setItemText(13,"13")
        self.comboBox.setItemText(14,"14")
        self.comboBox.setItemText(15,"15")
        self.comboBox.setItemText(16,"16")
        self.comboBox.setItemText(17,"17")
        self.comboBox.setItemText(18,"18")
        self.comboBox.setItemText(19,"19")
        self.comboBox.setItemText(20,"20")
        self.comboBox.setItemText(21,"21")
        self.comboBox.setItemText(22,"22")
        self.comboBox.setItemText(23,"23")
        self.comboBox.setItemText(24,"24")
        self.comboBox.setItemText(25,"25")
        self.comboBox.setItemText(26,"26")
        self.comboBox.setItemText(27,"27")
        self.comboBox.setItemText(28,"28")
        self.comboBox.setItemText(29,"29")
        self.comboBox.setItemText(30,"30")
        self.comboBox.setItemText(31,"31")
        self.label_15.setText("<html><head/><body><p><span style=\" font-size:9pt; color:#d0d0d0;\">Day</span></p></body></html>")
        self.label_3.setText("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Student Name </span><span style=\" font-size:10pt; font-weight:600; color:#ff0000;\">  *</span></p></body></html>")
        self.label_13.setText("<html><head/><body><p><span style=\" font-size:9pt; color:#d0d0d0;\">Year</span></p></body></html>")
        self.label_12.setText("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600; color:#000000;\">Exams End</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600; color:#ff0000;\">  *</span></p></body></html>")
        self.label_5.setText("<html><head/><body><p><span style=\" font-size:9pt; color:#d0d0d0;\">Last Name</span></p></body></html>")
        self.label_11.setText("<html><head/><body><p><span style=\" font-size:9pt; color:#d0d0d0;\">Year</span></p></body></html>")
        self.comboBox_4.setItemText(1,"2020")
        self.comboBox_4.setItemText(2,"2019")
        self.comboBox_4.setItemText(3,"2018")
        self.comboBox_4.setItemText(4,"2017")
        self.comboBox_4.setItemText(5,"2016")
        self.comboBox_4.setItemText(6,"2015")
        self.comboBox_4.setItemText(7, "2014")
        self.comboBox_4.setItemText(8,"2013")
        self.comboBox_4.setItemText(9,"2012")
        self.comboBox_4.setItemText(10,"2011")
        self.comboBox_4.setItemText(11,"2010")
        self.comboBox_4.setItemText(12,"2009")
        self.label.setText("<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Exam Registration Form</span></p></body></html>")
        self.comboBox_2.setItemText(1,"January")
        self.comboBox_2.setItemText(2,"February")
        self.comboBox_2.setItemText(3,"March")
        self.comboBox_2.setItemText(4,"April")
        self.comboBox_2.setItemText(5,"May")
        self.comboBox_2.setItemText(6,"June")
        self.comboBox_2.setItemText(7,"July")
        self.comboBox_2.setItemText(8,"August")
        self.comboBox_2.setItemText(9,"September")
        self.comboBox_2.setItemText(10,"October")
        self.comboBox_2.setItemText(11,"November")
        self.comboBox_2.setItemText(12,"December")
        self.label_2.setText("<html><head/><body><p align=\"justify\"><span style=\" font-size:9pt;\">Clearly fill the form below and ensure to indicate the courses registered for.</span></p></body></html>")
        self.comboBox_3.setItemText(1,"2020")
        self.comboBox_3.setItemText(2,"2019")
        self.comboBox_3.setItemText(3,"2018")
        self.comboBox_3.setItemText(4,"2017")
        self.comboBox_3.setItemText(5,"2016")
        self.comboBox_3.setItemText(6,"2015")
        self.comboBox_3.setItemText(7,"2014")
        self.comboBox_3.setItemText(8,"2013")
        self.comboBox_3.setItemText(9,"2012")
        self.comboBox_3.setItemText(10,"2011")
        self.comboBox_3.setItemText(11,"2010")
        self.comboBox_3.setItemText(12,"2009")
        self.pushButton.setText("Submit")
        self.label_10.setText("<html><head/><body><p><span style=\" font-size:9pt; color:#d0d0d0;\">Month</span></p></body></html>")
        self.label_16.setText("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600;\">Comment</span></p></body></html>")
        self.label_14.setText("<html><head/><body><p><span style=\" font-size:9pt; color:#d0d0d0;\">Month</span></p></body></html>")
        self.comboBox_5.setItemText(1,"1")
        self.comboBox_5.setItemText(2,"2")
        self.comboBox_5.setItemText(3,"3")
        self.comboBox_5.setItemText(4,"4")
        self.comboBox_5.setItemText(5,"5")
        self.comboBox_5.setItemText(6,"6")
        self.comboBox_5.setItemText(7,"7")
        self.comboBox_5.setItemText(8,"8")
        self.comboBox_5.setItemText(9,"9")
        self.comboBox_5.setItemText(10,"10")
        self.comboBox_5.setItemText(11,"11")
        self.comboBox_5.setItemText(12,"12")
        self.comboBox_5.setItemText(13,"13")
        self.comboBox_5.setItemText(14,"14")
        self.comboBox_5.setItemText(15,"15")
        self.comboBox_5.setItemText(16,"16")
        self.comboBox_5.setItemText(17,"17")
        self.comboBox_5.setItemText(18,"18")
        self.comboBox_5.setItemText(19,"19")
        self.comboBox_5.setItemText(20,"20")
        self.comboBox_5.setItemText(21,"21")
        self.comboBox_5.setItemText(22,"22")
        self.comboBox_5.setItemText(23,"23")
        self.comboBox_5.setItemText(24,"24")
        self.comboBox_5.setItemText(25,"25")
        self.comboBox_5.setItemText(26,"26")
        self.comboBox_5.setItemText(27,"27")
        self.comboBox_5.setItemText(28,"28")
        self.comboBox_5.setItemText(29,"29")
        self.comboBox_5.setItemText(30,"30")
        self.comboBox_5.setItemText(31,"31")
        self.label_4.setText("<html><head/><body><p><span style=\" font-size:9pt; color:#d0d0d0;\">First Name</span></p></body></html>")
        self.label_8.setText("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600; color:#000000;\">Exams Start</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600; color:#ff0000;\">  *</span></p></body></html>")
        self.comboBox_6.setItemText(1,"January")
        self.comboBox_6.setItemText(2,"February")
        self.comboBox_6.setItemText(3,"March")
        self.comboBox_6.setItemText(4,"April")
        self.comboBox_6.setItemText(5,"May")
        self.comboBox_6.setItemText(6,"June")
        self.comboBox_6.setItemText(7,"July")
        self.comboBox_6.setItemText(8,"August")
        self.comboBox_6.setItemText(9, "September")
        self.comboBox_6.setItemText(10,"October")
        self.comboBox_6.setItemText(11,"November")
        self.comboBox_6.setItemText(12,"December")
        self.label_7.setText("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600;\">Registered Course </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600; color:#ff0000;\">  *</span></p></body></html>")
        self.label_17.setText("<html><head/><body><p><span style=\" font-size:9pt; color:#d0d0d0;\">Day</span></p></body></html>")
        self.pushButton.clicked.connect(lambda checked: sumbit(self));

if __name__ == "__main__":
      app = QtWidgets.QApplication(sys.argv)
      MainWindow= QtWidgets.QMainWindow()
      ui=F()
      ui.exam(MainWindow)
      MainWindow.show()
      sys.exit(app.exec_())



